apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: enforce
  rules:
  - name: validate-image-tag
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "L'utilisation du tag 'latest' est interdite."
      pattern:
        spec:
          containers:
          - image: "!*:latest"

